export const CATEGORIES = [
  'Informática',
  'Eletrônicos',
  'Móveis',
  'Roupas',
  'Calçados',
  'Automóveis',
  'Imóveis',
  'Serviços domésticos',
  'Aulas particulares',
  'Saúde e beleza',
  'Esportes',
  'Brinquedos',
  'Alimentos',
  'Instrumentos musicais',
  'Livros',
  'Eventos',
  'Pet shop',
  'Viagens',
  'Ferramentas',
  'Arte e artesanato',
];
